ALTER TABLE army ADD FOREIGN KEY (codex) REFERENCES codex(id) ON DELETE RESTRICT;
ALTER TABLE army ADD FOREIGN KEY (userid) REFERENCES `user`(id) ON DELETE RESTRICT;
ALTER TABLE army ADD FOREIGN KEY (gamesystem) REFERENCES gamesystem(id) ON DELETE RESTRICT;
ALTER TABLE battle ADD FOREIGN KEY (player1) REFERENCES army(id) ON DELETE RESTRICT;
ALTER TABLE battle ADD FOREIGN KEY (player2) REFERENCES army(id) ON DELETE RESTRICT;
ALTER TABLE battle ADD FOREIGN KEY (mission) REFERENCES mission(id) ON DELETE RESTRICT;
ALTER TABLE battle ADD FOREIGN KEY (userid) REFERENCES `user`(id) ON DELETE RESTRICT;
ALTER TABLE battle ADD FOREIGN KEY (battletypeid) REFERENCES battletype(id) ON DELETE RESTRICT;
ALTER TABLE battle ADD FOREIGN KEY (multibattle) REFERENCES multibattle(id) ON DELETE RESTRICT;
ALTER TABLE battle ADD FOREIGN KEY (gamesystem) REFERENCES gamesystem(id) ON DELETE RESTRICT;
ALTER TABLE battletype ADD FOREIGN KEY (parent) REFERENCES battletype(id) ON DELETE RESTRICT;
ALTER TABLE codex ADD FOREIGN KEY (gamesystem) REFERENCES gamesystem(id) ON DELETE RESTRICT;
ALTER TABLE mission ADD FOREIGN KEY (gamesystem) REFERENCES gamesystem(id) ON DELETE RESTRICT;
ALTER TABLE multibattlearmy ADD FOREIGN KEY (army_id) REFERENCES army(id) ON DELETE RESTRICT;
ALTER TABLE multibattlearmy ADD FOREIGN KEY (multibattle) REFERENCES multibattle(id) ON DELETE RESTRICT;

ALTER TABLE image ADD FOREIGN KEY (imagecategoryid) REFERENCES imagecategory(id) ON DELETE RESTRICT;

-- QUESTIONAIRE !!!

ALTER TABLE `user` CHANGE `groupid` `groupid` BIGINT( 20 ) NOT NULL DEFAULT '0';
ALTER TABLE `user` ADD FOREIGN KEY (groupid) REFERENCES usergroup(id) ON DELETE RESTRICT;
ALTER TABLE `user` ADD FOREIGN KEY (newgroup) REFERENCES usergroup(id) ON DELETE SET NULL;
ALTER TABLE userrights ADD FOREIGN KEY (usergroupid) REFERENCES usergroup(id) ON DELETE CASCADE;

INSERT INTO dbversion(sql_id, sql_subid) VALUES (31, 0);