-- from now on mysql 5 only
ALTER TABLE `army`  ENGINE = innodb;
ALTER TABLE `battle`  ENGINE = innodb;
ALTER TABLE `battletype`  ENGINE = innodb;
ALTER TABLE `codex`  ENGINE = innodb;
ALTER TABLE `dbversion`  ENGINE = innodb;
ALTER TABLE `extendible`  ENGINE = innodb;
ALTER TABLE `gamesystem`  ENGINE = innodb;
ALTER TABLE `guestbook`  ENGINE = innodb;
ALTER TABLE `image`  ENGINE = innodb;
ALTER TABLE `imagecategory`  ENGINE = innodb;
ALTER TABLE `mailer`  ENGINE = innodb;
ALTER TABLE `mission`  ENGINE = innodb;
ALTER TABLE `multibattle`  ENGINE = innodb;
ALTER TABLE `multibattlearmy`  ENGINE = innodb;
ALTER TABLE `newsletter`  ENGINE = innodb;
ALTER TABLE `page`  ENGINE = innodb;
ALTER TABLE `pagestatistic`  ENGINE = innodb;
ALTER TABLE `question`  ENGINE = innodb;
ALTER TABLE `questionaire`  ENGINE = innodb;
ALTER TABLE `questionaireanswers`  ENGINE = innodb;
ALTER TABLE `questionaireuser`  ENGINE = innodb;
ALTER TABLE `questionanswer`  ENGINE = innodb;
ALTER TABLE `questionanswertype`  ENGINE = innodb;
ALTER TABLE `session`  ENGINE = innodb;
ALTER TABLE `setting`  ENGINE = innodb;
ALTER TABLE `template`  ENGINE = innodb;
ALTER TABLE `user`  ENGINE = innodb;
ALTER TABLE `usergroup`  ENGINE = innodb;
ALTER TABLE `userrights`  ENGINE = innodb;

INSERT INTO dbversion(sql_id, sql_subid) VALUES (30, 0);